import type { Metadata } from "next";
import localFont from "next/font/local";
import { cn } from "@godsreveal/ui";
import "@godsreveal/ui/globals.css";
import "globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(geistSans.variable, geistMono.variable, "bg-primary/10")}
      >
        {children}
      </body>
    </html>
  );
}
